title: Nicholas Resendez
subtitle: Portfolio website
description: >- # this means to ignore newlines until "baseurl:"
  Nicholas Resendez

url: "https://nicholasresendez.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:



# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Nicholas Resendez
author_bio: Nicholas Resendez is an American security researcher, Internet programmer, and Internet entrepreneur. He has provided security research services to Apple Inc, Microsoft, AT&T, U.S Department of Defense, and more. Nicholas is the Founder of Grindez & uALREADY. Nicholas graduated from University of Wisconsin–Milwaukee in 2019 with a Bachelor's degree in Information Technology Management and Marketing. Nicholas currently holds a Wisconsin Real Estate License.
author_email: "admin@grindez.com"
author_location: Los Angeles, CA
author_website_url: "https://nicholasresendez.com"
typewrite-text: 


# Experiences
author_work_experiences:

            - company_name: Grindez
              company_logo: grindez.png
              company_url: https://grindez.com
              designation: Founder
              description: Grindez.com is the worlds p2p work marketplace platform, cryptocurrency payments enabled.
              visibility: true
            - company_name: Entrepreneur
              company_logo: entrepreneur.png
              company_url: https://entrepreneur.com/author/nicholas-resendez
              designation: Contributing Writer
              description: August 2021 - Present
              visibility: true
            - company_name: LunarCRUSH
              company_logo: lunarcrush.png
              company_url: https://lunarcrush.com
              designation: Growth Specialist
              description: Feb 2020 – Sep 2020
              visibility: true
            - company_name: Socialeads
              company_logo: socialeads.png
              company_url: https://socialeads.com
              designation: Data Science
              description: Nov 2018 – Sep 2019
              visibility: true
            - company_name: University of Wisconsin-Milwaukee
              company_logo: uwm.png
              company_url: https://uwm.edu/studentsuccess
              designation: Web Developer
              description: Jan 2017 – May 2019
              visibility: true
            - company_name: Laughlin Constable
              company_logo: laughlin.png
              company_url: https://www.laughlin.com/
              designation: Data Science Intern
              description: Jun 2018 – Sep 2018
              visibility: true
            - company_name: AppBrewery
              company_logo: brew.png
              company_url: https://www.appbrewery.co/
              designation: Mobile & Web Software Developer Intern
              description: Jul 2017 – Nov 2017
              visibility: true
            - company_name: Realty Executives Integrity 
              company_logo: realty.png
              company_url: https://www.realtyexecutives.com/
              designation: Marketing + Front Desk Associate
              description: Sep 2015 – Nov 2016
              visibility: true

# Education
author_education_details:
              - college_logo: uwm.png
                college_name: University of Wisconsin–Milwaukee
                college_url: https://uwm.edu
                college_degree: Information Technology Management, Marketing
                description: Sep 2015 - May 2019
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true

# social links
twitter_username: nickresendez
github_username:  nirholas
linkedin_username: nixholas
instagram_username: nirholas
medium_username: nrese

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )



# wakatime username (coding activity)
wakatime_username: sujaykundu777



# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
